version: "3"

services:
  grav-php:
    image: grav-php:1.7.43
    build: php
    volumes:
      - grav-files:/srv/grav/web/user
      - grav-backup:/srv/grav/web/backup


  grav-web:
    image: grav-web:1.7.43
    build: nginx
    environment:
      NODE_ENV: dev
    ports:
      - "7070:80"
    volumes:
      - grav-files:/srv/grav/web/user
      - grav-backup:/srv/grav/web/backup
    depends_on:
      - grav-php

volumes:
    grav-files:
    grav-backup: